name: Build and Store Artifacts

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  id-token: write

env:
  DENO_VERSION: v1.36.0
  BUILD_DIR: bin
  ARTIFACT_NAME: build-artifacts

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [x86_64-pc-windows-msvc, x86_64-apple-darwin, aarch64-apple-darwin, x86_64-unknown-linux-gnu]
      fail-fast: false

    steps:
      - name: Cache Deno Modules
        uses: actions/cache@v3
        with:
          path: ~/.deno/cache
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deps.ts') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Check for Commits Made Today
        id: check_commits
        run: |
          COMMITS=$(git log --since="${{ steps.date.outputs.date }}T00:00:00" --oneline)
          if [ -z "$COMMITS" ]; then
            echo "No commits made today. Exiting."
            exit 0
          fi
          echo "Commits found for today."

      - name: Compile Code for ${{ matrix.platform }}
        run: |
          deno compile --target ${{ matrix.platform }} --output ${BUILD_DIR}/seventy-${{ matrix.platform }} main/seventy.ts

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${BUILD_DIR}/

      - name: Compress Build Artifacts
        run: zip -r ${BUILD_DIR}/build-artifacts.zip ${BUILD_DIR}/

      - name: Upload Compressed Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${env.ARTIFACT_NAME}-compressed
          path: ${BUILD_DIR}/build-artifacts.zip


  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Lint Code
        run: deno lint

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}
      
      # No tests are made yet, coming soon
      # - name: Run Tests
      #   run: deno test --unstable
