on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.36.0

      - name: Compile project for multiple platforms
        run: |
          echo "Compiling for Windows (x86_64)"
          deno compile --target x86_64-pc-windows-msvc --output bin/seventy-win main/seventy.ts
          
          echo "Compiling for macOS (x86_64)"
          deno compile --target x86_64-apple-darwin --output bin/seventy-mac main/seventy.ts
          
          echo "Compiling for macOS (ARM)"
          deno compile --target aarch64-apple-darwin --output bin/seventy-mac-arm main/seventy.ts
          
          echo "Compiling for Linux (x86_64)"
          deno compile --target x86_64-unknown-linux-gnu --output bin/seventy-linux main/seventy.ts

      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v4
        with:
          name: seventy-win
          path: bin/seventy-win.exe

      - name: Upload macOS x86_64 build artifact
        uses: actions/upload-artifact@v4
        with:
          name: seventy-mac
          path: bin/seventy-mac

      - name: Upload macOS ARM build artifact
        uses: actions/upload-artifact@v4
        with:
          name: seventy-mac-arm
          path: bin/seventy-mac-arm

      - name: Upload Linux x86_64 build artifact
        uses: actions/upload-artifact@v4
        with:
          name: seventy-linux
          path: bin/seventy-linux
